### ISSUE TITLE
Java Error: NoSuchMethodError

### ISSUE THREAD

**Issue by rob-01** [goliasz/snowplow-flink-enriched2json#1]
I'm getting this error on flink 1.2.1. This is the "exceptions" output from the failed flink job. From my initial research, a nosuchmethoderror has something to do with scala dependencies. I'm using a FatJar per the instructions, and have customized only the hardcoded kafka values in the Enriched2Json.scala file. I compiled the jar on local desktop, which ran without errors. I then uploaded to the flink server to run the task. Any ideas about what I need to do differently?

**Root exception**
```
java.lang.NoSuchMethodError: scala.collection.immutable.$colon$colon.hd$1()Ljava/lang/Object;
	at org.json4s.MonadicJValue.$bslash(MonadicJValue.scala:18)
	at com.snowplowanalytics.snowplow.analytics.scalasdk.json.JsonShredder$.parseContexts(JsonShredder.scala:172)
	at com.snowplowanalytics.snowplow.analytics.scalasdk.json.EventTransformer$$anonfun$6.apply(EventTransformer.scala:48)
	at com.snowplowanalytics.snowplow.analytics.scalasdk.json.EventTransformer$$anonfun$6.apply(EventTransformer.scala:48)
	at com.snowplowanalytics.snowplow.analytics.scalasdk.json.EventTransformer$.com$snowplowanalytics$snowplow$analytics$scalasdk$json$EventTransformer$$converter(EventTransformer.scala:202)
	at com.snowplowanalytics.snowplow.analytics.scalasdk.json.EventTransformer$$anonfun$8.apply(EventTransformer.scala:255)
	at com.snowplowanalytics.snowplow.analytics.scalasdk.json.EventTransformer$$anonfun$8.apply(EventTransformer.scala:255)
	at scala.collection.immutable.List.map(List.scala:277)
	at com.snowplowanalytics.snowplow.analytics.scalasdk.json.EventTransformer$.jsonifyGoodEvent(EventTransformer.scala:255)
	at com.snowplowanalytics.snowplow.analytics.scalasdk.json.EventTransformer$.transform(EventTransformer.scala:272)
	at com.rbox24.Enriched2JSON$$anonfun$main$1.apply(Enriched2Json.scala:36)
	at com.rbox24.Enriched2JSON$$anonfun$main$1.apply(Enriched2Json.scala:36)
	at org.apache.flink.streaming.api.scala.DataStream$$anon$4.map(DataStream.scala:521)
	at org.apache.flink.streaming.api.operators.StreamMap.processElement(StreamMap.java:38)
	at org.apache.flink.streaming.runtime.io.StreamInputProcessor.processInput(StreamInputProcessor.java:185)
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask.run(OneInputStreamTask.java:63)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:261)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:665)
	at java.lang.Thread.run(Thread.java:745)
```

**Map -> Filter -> Flat Map -> Sink: Unnamed (1/1)**
```
java.lang.NoSuchMethodError: scala.collection.immutable.$colon$colon.hd$1()Ljava/lang/Object;
	at org.json4s.MonadicJValue.$bslash(MonadicJValue.scala:18)
	at com.snowplowanalytics.snowplow.analytics.scalasdk.json.JsonShredder$.parseContexts(JsonShredder.scala:172)
	at com.snowplowanalytics.snowplow.analytics.scalasdk.json.EventTransformer$$anonfun$6.apply(EventTransformer.scala:48)
	at com.snowplowanalytics.snowplow.analytics.scalasdk.json.EventTransformer$$anonfun$6.apply(EventTransformer.scala:48)
	at com.snowplowanalytics.snowplow.analytics.scalasdk.json.EventTransformer$.com$snowplowanalytics$snowplow$analytics$scalasdk$json$EventTransformer$$converter(EventTransformer.scala:202)
	at com.snowplowanalytics.snowplow.analytics.scalasdk.json.EventTransformer$$anonfun$8.apply(EventTransformer.scala:255)
	at com.snowplowanalytics.snowplow.analytics.scalasdk.json.EventTransformer$$anonfun$8.apply(EventTransformer.scala:255)
	at scala.collection.immutable.List.map(List.scala:277)
	at com.snowplowanalytics.snowplow.analytics.scalasdk.json.EventTransformer$.jsonifyGoodEvent(EventTransformer.scala:255)
	at com.snowplowanalytics.snowplow.analytics.scalasdk.json.EventTransformer$.transform(EventTransformer.scala:272)
	at com.rbox24.Enriched2JSON$$anonfun$main$1.apply(Enriched2Json.scala:36)
	at com.rbox24.Enriched2JSON$$anonfun$main$1.apply(Enriched2Json.scala:36)
	at org.apache.flink.streaming.api.scala.DataStream$$anon$4.map(DataStream.scala:521)
	at org.apache.flink.streaming.api.operators.StreamMap.processElement(StreamMap.java:38)
	at org.apache.flink.streaming.runtime.io.StreamInputProcessor.processInput(StreamInputProcessor.java:185)
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask.run(OneInputStreamTask.java:63)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:261)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:665)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by rob-01** [comment]
This was resolved by changing the scala version on the flink server (not inside the Fat JAR) to 2.10. It was previously 2.11.
